fragment MemberFields on Membership {
  handle
  id
  createdAt
  isFoundingMember
  isCouncilMember
  rootAccount
  externalResources {
    type
    value
  }
  roles {
    status {
      __typename
    }
    groupId
    isLead
  }
}

query getMembers {
  memberships(
    limit: 500000
    where: {
      externalResources_some: { type_eq: DISCORD }
    }
  ) {
    ...MemberFields
  }
}
